// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY8tTOOCN5IWIwG4H3YPdjhPP83Y0mepE',
    appId: '1:604397919628:web:5a309beec6ab1aed678aa9',
    messagingSenderId: '604397919628',
    projectId: 'codingera-e80b5',
    authDomain: 'codingera-e80b5.firebaseapp.com',
    storageBucket: 'codingera-e80b5.firebasestorage.app',
    measurementId: 'G-143XR262S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcAlQkxt8Vmlfnz6P4I7uJP4sqG8Oy54U',
    appId: '1:604397919628:android:b9dae9254a42483c678aa9',
    messagingSenderId: '604397919628',
    projectId: 'codingera-e80b5',
    storageBucket: 'codingera-e80b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtA1T8IH0H4vflySavcfTv9r4V9jGCpWw',
    appId: '1:604397919628:ios:ed90c6cefec1ed2f678aa9',
    messagingSenderId: '604397919628',
    projectId: 'codingera-e80b5',
    storageBucket: 'codingera-e80b5.firebasestorage.app',
    iosBundleId: 'com.example.codingera2',
  );
}
